name: json_to_class_generator
description: Simple generator to repro json serializable builder bug
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  build: ^2.0.1
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.2
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  lints: ^1.0.0
